version: 2
updates:
  - package-ecosystem: maven
    directory: /backend/api-core
    schedule: {interval: weekly}
    groups:
      api-java: {patterns: ["*"]}
  - package-ecosystem: maven
    directory: /backend/pipeline-consumer
    schedule: {interval: weekly}
    groups:
      consumer-java: {patterns: ["*"]}
  - package-ecosystem: maven
    directory: /backend/openhim-mediators
    schedule: {interval: weekly}
    groups:
      mediators-java: {patterns: ["*"]}
  - package-ecosystem: npm
    directory: /frontend
    schedule: {interval: weekly}
    groups:
      frontend: {patterns: ["*"]}
  - package-ecosystem: npm
    directory: /backend/iol-mediator
    schedule: {interval: weekly}
    groups:
      mediator-node: {patterns: ["*"]}
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
