proxy_http_version 1.1;
proxy_ssl_server_name on;
proxy_ssl_name api-core;
proxy_ssl_trusted_certificate /run/tls/ca.pem;
proxy_ssl_verify on;
proxy_ssl_verify_depth 2;
proxy_ssl_certificate /run/tls/nginx.crt;
proxy_ssl_certificate_key /run/tls/nginx.key;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header Authorization $http_authorization;
proxy_set_header Connection "";
proxy_connect_timeout 10s;
proxy_send_timeout 120s;
