foreground = yes
pid =
debug = notice

[clamav]
client = no
accept = 0.0.0.0:3311
connect = 127.0.0.1:3310
cert = /run/tls/clamav.crt
key = /run/tls/clamav.key
CAfile = /run/tls/ca.pem
verifyChain = yes
checkHost = api-core
sslVersionMin = TLSv1.2
options = NO_SSLv2
options = NO_SSLv3
