<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.iol.openhim</groupId>
        <artifactId>openhim-mediator-iol-standard-packs</artifactId>
        <version>1.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>openhim-mediator-iol-iso20022</artifactId>
    <name>OpenHIM Mediator IOL ISO 20022</name>

    <dependencies>
        <dependency>
            <groupId>com.iol.openhim</groupId>
            <artifactId>mediator-runtime</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.prowidesoftware</groupId>
            <artifactId>pw-iso20022</artifactId>
            <version>${prowide-iso20022.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
